### PR TITLE
Adds support for Android's legacy mode.

### PR DESCRIPTION
**Pull request by matteobortolazzo**

### CODE REVIEW

**Comment by GuidoNeele** [comment]
Hi Matteo,

Great!! The only thing I need is being able to switch modes. This is a far easier solution for the same problem :-)

Thanks!

**Comment by matteobortolazzo** [comment]
Cool, glad to hear that.
I have another feature I want to add to Android. It I can make it work I will add that to this PR and then release everything as 4.1.0

**Comment by matteobortolazzo** [comment]
@GuidoNeele 4.1.0 published

**Comment by GuidoNeele** [comment]
Great will test it tomorrow!

**Pull request merged**
