### PR TITLE
IOS Renderer rewrite + bullit alignment

### PR DESCRIPTION
**Pull request by DaanKwilia**

### CODE REVIEW

**Comment by matteobortolazzo** [comment]
Hi @DaanKwilia,

Could PR #105 with the issues you had with iOS??

**Comment by DaanKwilia** [comment]
Perhaps, but in the solution I supplied, you don't have to calculate where has been clicked, the native IOS control handles that, so you will be more future proof.

**Comment by IeuanWalker** [comment]
On iOS links and phone numbers are clickable, but email links are not. 

Also seams to have an issue with scrolling.
The control is wrapped in a scrollview, but is only scrollable when the view is refreshed with hot reload. Wasnt an issue on older versions

**Comment by matteobortolazzo** [comment]
@DaanKwilia hello,
I noticed some padding in v5, is it something that can be fixed?

**Comment by DaanKwilia** [comment]
Perhaps, I don’t have a lot of time lately. I’ll check the difference when I have some spare time. If someone else is able to fix it he’s most welcome 😊

**Comment by matteobortolazzo** [comment]
@DaanKwilia @IeuanWalker alpha 4 release, can you check that it works as expected please?

**Comment by DaanKwilia** [comment]
Hi Matteo,

 

It is not working for me, I see a difference on android and IOS.

Android:



 

IOS:



As you can see on IOS the htmllabels are overlapping, in the alpha 3 this was not the case.

**Comment by DaanKwilia** [comment]
Hi Matteo,

 

It is not working for me, I see a difference on android and IOS.

Android:
android

IOS:
ios

As you can see on IOS the htmllabels are overlapping, in the alpha 3 this was not the case.

**Comment by DaanKwilia** [comment]
Hi @matteobortolazzo,

An update on my previous finding.
I have altered the xaml of the overlapping controls, now is seems to work and have no issues on IOS or Android. Margins also seem to be fine.

**Comment by matteobortolazzo** [comment]
@DaanKwilia so do you think v5 is good enough for a stable release?

**Comment by DaanKwilia** [comment]
@matteobortolazzo 
Well, we are using the alfa 3 version for some time now, no strange things encountered. The alfa 4 version seems oke with the changes we made.
In UWP there is still an issue with special characters, but that is also a problem in the current v4.
So if you ask me, then yes.

**Comment by matteobortolazzo** [comment]
Cool, then I will release it by the end of the week

**Pull request merged**
