### PR TITLE
Fix issue #58

### PR DESCRIPTION
**Pull request by csteeg**
Include apple-system on font-family

### CODE REVIEW

**Comment by matteobortolazzo** [comment]
Thank you very much! :)

**Comment by matteobortolazzo** [comment]
Hi @DevEddy! so this pull request exists because of #58.
I don't understand why a pull request for fixing custom fonts breaks custom fonts...
@csteeg Can you help us understand what's happening? Use you using two different version of iOS maybe?

**Comment by DevEddy** [comment]
I would try to debug it but multitargeting doesn't work for me in the newest VS on Windows or Mac..

**Comment by matteobortolazzo** [comment]
What's the error?

**Comment by csteeg** [comment]
@DevEddy so you set the font family to a font that's embedded in included in your iOS project? This fix was indeed to let that work, if -apple-system wasn't included, on my end the font did not show correctly. What version of iOS did you test this on?

**Comment by DevEddy** [comment]
Before this update everything worked well for me.
I am using the newest iOS 12.3

@matteobortolazzo I don't remember, I will need to test it onre more time.

-- Eddy

**Comment by matteobortolazzo** [comment]
@csteeg @DevEddy 
since I am unable understand and test this issue I removed the build from NuGet for now.

**Pull request merged**
