### PR TITLE
Fix NullReferenceException launching email on iOS

### PR DESCRIPTION
**Pull request by IeuanWalker**
Previous code + error -
image

Updated code - 
image

### CODE REVIEW

**Comment by matteobortolazzo** [comment]
@IeuanWalker Please can you generate a NuGet with version 5.0.0-alpha2? (just check "Generate NuGet package on Build, and compile in Release).

**Comment by IeuanWalker** [comment]
@matteobortolazzo thanks, I need other people on my team to be able to download the latest version of my code, can I just include the .nupkg in the solution and add a new nuget package source pointing to that location? Not sure if that would work for other people as it would be using my file location. (i.e. D drive)

Here is the .nupkg though - 
[Xam.Plugin.HtmlLabel.5.0.0-alpha2.nupkg.zip](https://github.com/matteobortolazzo/HtmlLabelPlugin/files/4831621/Xam.Plugin.HtmlLabel.5.0.0-alpha2.nupkg.zip)

**Comment by matteobortolazzo** [comment]
Sorry, what do you mean by "your files"? The NuGet should not contain any info about the files outside the project

**Comment by matteobortolazzo** [comment]
Submitted BTW

**Pull request merged**
