### PR TITLE
Remove Padding Kludge to resolve iOS freezing.

### PR DESCRIPTION
**Pull request by bakerhillpins**
https://github.com/matteobortolazzo/HtmlLabelPlugin/issues/135

Remove the UITextViewFixedWithKludge class which was attempting to manage padding changes to the Native UI control. In some circumstances it resulted in a recursive call to the Setup() method in the UITextViewFixedWithKludge class which made iOS appear to freeze. Return to original code that's based upon use in Xamarin.Forms.

I noted a few things with respect to the way XF has the render setup and fixed those as well.

### CODE REVIEW

**Comment by bakerhillpins** [comment]
It looks like the UWP and Android versions both extend the XF Label implementation and fixup Links/URLs and some other basic HTML rendering.  But iOS is it's own implementation. Maybe it should be changed to also extend the Render?

**Comment by matteobortolazzo** [comment]
Hi @bakerhillpins sorry for my late checks but I am very busy. I found the [PR ](https://github.com/matteobortolazzo/HtmlLabelPlugin/pull/104) where iOS implementation has changed. Maybe you can check if the issues it tries to fix are still there.

Till v4 iOS was using XF, then some had issues and I decided to accept PRs for v5 which rewrites it. But then other stuff broke. If everything is fine I'll try to release a preview

**Comment by bakerhillpins** [comment]
> Hi @bakerhillpins sorry for my late checks but I am very busy. I found the [PR ](https://github.com/matteobortolazzo/HtmlLabelPlugin/pull/104) where iOS implementation has changed. Maybe you can check if the issues it tries to fix are still there.

@matteobortolazzo  No worries, we've all got other stuff going on.  Looking through the PR and those associated with it it's not really clear what if any problem exists and there are no example projects to load so there isn't really anything to go on. 

- the email click failure was addressed
- the overlap of adjacent labels appears to be a XAML issue based upon [feedback from the author](https://github.com/matteobortolazzo/HtmlLabelPlugin/pull/104#issuecomment-709022508).
- the scrolling issue is apparently an old Xamarin Forms issue

I've fiddled with padding in my app and it uses it appropriately and HotReload is working as well. I'm not sure what else we can go on here?

**Comment by bakerhillpins** [comment]
The interesting thing about the Kludge is that it appears to be styled after [Xamarin Forms code](https://github.com/xamarin/Xamarin.Forms/blob/02dee20dfa1365d0104758e534581d1fa5958990/Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs#L12) where they [subclass ](https://github.com/xamarin/Xamarin.Forms/blob/02dee20dfa1365d0104758e534581d1fa5958990/Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs#L681)`UIKit.UILabel` and add a `TextInsets` property to mimic padding.  In the local implementation, the code uses `UIKit.UITextView` which has insets built into it's implementation via it's `TextContainer` property. So the kludge doesn't appear to be valid here.

**Pull request merged**
